Repository dotkom/onlineweb-frontend, pull requests merged in 2019-09, with the labels that each got.

#288 Feat/stripe events
  src/App.tsx
  src/common/components/ResponsiveImage/index.tsx
  src/events/api/events.ts
  src/events/models/Attendee.ts
  src/events/models/Event.ts
  src/payments/api/paymentRelation.ts
  src/payments/components/EventPayment/index.tsx
  src/payments/components/Payment/CreatePaymentRelation.tsx
  src/payments/components/Payment/StripeForm.tsx
  src/payments/components/Payment/index.tsx
  src/payments/components/Payment/payment.less
  src/payments/components/Wallet/index.tsx
  src/payments/components/WebshopPayment/CartError.tsx
  src/payments/components/WebshopPayment/EmptyCart.tsx
  src/payments/components/WebshopPayment/index.tsx
  src/payments/index.tsx
  src/payments/models/Payment.ts
  src/payments/models/PaymentRelation.ts
  src/profile/api/orders.ts
  src/profile/components/Statistics/Orders/OrderBar.tsx
  src/profile/components/Statistics/Orders/OrderItemDonut.tsx
  src/profile/components/Statistics/Orders/index.tsx
  src/shop/models/index.ts
  src/shop/reducers/orderLines.ts
  src/webshop/api/index.ts
  src/webshop/models/index.ts
Labels: Priority: Critical

#296 display balance on wallet site
  src/App.tsx
  src/payments/components/Transactions/CreateTransaction/StripeForm.tsx
  src/profile/index.tsx
  src/profile/providers/UserProfile.tsx
Labels: Status: Design Phase

#299 Added 'Fremhevet plassering' to featured career opportunities.
  src/career/components/JobListItem.tsx
  src/career/less/career.less
Labels: Easy, Priority: Critical

#222 Add page to view a single article
  src/App.tsx
  src/articles/api/index.ts
  src/articles/components/ArticleView/ArticleByline.tsx
  src/articles/components/ArticleView/ArticleMeta.tsx
  src/articles/components/ArticleView/ArticleVideo.tsx
  src/articles/components/ArticleView/RelatedArticles/RelatedArticle.tsx
  src/articles/components/ArticleView/RelatedArticles/index.tsx
  src/articles/components/ArticleView/RelatedArticles/relatedArticle.less
  src/articles/components/ArticleView/articleView.less
  src/articles/components/ArticleView/index.tsx
  src/articles/components/ArticlesRouter.tsx
  src/articles/models/Article.ts
  src/common/components/Carousel/CarouselArrow.tsx
  src/common/components/Carousel/carousel.less
  src/common/components/Carousel/index.tsx
  src/common/components/Heading/index.tsx
  src/common/utils/PrefetchState.ts
  src/common/utils/api.ts
  src/events/components/DetailView/detail.less
  src/events/components/DetailView/index.tsx
  src/frontpage/components/Articles/MainArticle.tsx
  src/frontpage/components/Articles/SmallArticle.tsx
Labels: App: Article, Status: Design Phase, Type: Feature, Work In Progress
